export:
	python manage.py render_guia --config=Export --guide-version=3 --element=1 --archive --filename=guia-1.zip

about:
	python manage.py render_about --config=Export

run:
	python manage.py runserver
